CREATE TABLE `adresa_sidlo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `about` varchar(100) COLLATE utf8_bin NOT NULL,
  `nachaziSeNaUzemiStatu` varchar(80) COLLATE utf8_bin DEFAULT NULL,
  `zaznamAktualizaceDatumCas` datetime DEFAULT NULL,
  `zaznamIdentifikator` varchar(40) COLLATE utf8_bin NOT NULL,
  `zaznamPlatnostDatum` datetime DEFAULT NULL,
  `adresniMistoKod` int(11) DEFAULT NULL,
  `castObceKod` int(11) DEFAULT NULL,
  `obecKod` int(11) DEFAULT NULL,
  `obecNazev` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `objektCisloDomovni` int(11) DEFAULT NULL,
  `psc` int(11) DEFAULT NULL,
  `uliceKod` int(11) DEFAULT NULL,
  `uliceNazev` varchar(60) COLLATE utf8_bin DEFAULT NULL,
  `obec` varchar(90) COLLATE utf8_bin DEFAULT NULL,
  `title` varchar(180) COLLATE utf8_bin DEFAULT NULL,
  `adresaKvalifikatorKod` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `mestskyObvodMestskaCastKod` int(11) DEFAULT NULL,
  `mestskyObvodMestskaCastNazev` varchar(40) COLLATE utf8_bin DEFAULT NULL,
  `objektCisloOrientacni` varchar(10) COLLATE utf8_bin DEFAULT NULL,
  `mestskyObvodMestskaCast` varchar(110) COLLATE utf8_bin DEFAULT NULL,
  `adresaText` varchar(180) COLLATE utf8_bin DEFAULT NULL,
  `modified` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `about` (`about`),
  UNIQUE KEY `zaznamIdentifikator` (`zaznamIdentifikator`),
  KEY `nachaziSeNaUzemiStatu` (`nachaziSeNaUzemiStatu`),
  KEY `zaznamAktualizaceDatumCas` (`zaznamAktualizaceDatumCas`),
  KEY `zaznamPlatnostDatum` (`zaznamPlatnostDatum`),
  KEY `adresniMistoKod` (`adresniMistoKod`),
  KEY `castObceKod` (`castObceKod`),
  KEY `obecKod` (`obecKod`),
  KEY `obecNazev` (`obecNazev`),
  KEY `objektCisloDomovni` (`objektCisloDomovni`),
  KEY `psc` (`psc`),
  KEY `uliceKod` (`uliceKod`),
  KEY `uliceNazev` (`uliceNazev`),
  KEY `obec` (`obec`),
  KEY `title` (`title`),
  KEY `adresaKvalifikatorKod` (`adresaKvalifikatorKod`),
  KEY `mestskyObvodMestskaCastKod` (`mestskyObvodMestskaCastKod`),
  KEY `mestskyObvodMestskaCastNazev` (`mestskyObvodMestskaCastNazev`),
  KEY `objektCisloOrientacni` (`objektCisloOrientacni`),
  KEY `mestskyObvodMestskaCast` (`mestskyObvodMestskaCast`),
  KEY `adresaText` (`adresaText`),
  KEY `modified` (`modified`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
