CREATE TABLE `rozhodnuti` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `about` varchar(150) COLLATE utf8_bin NOT NULL,
  `castkaPozadovana` decimal(15,2) DEFAULT NULL,
  `castkaRozhodnuta` decimal(15,2) DEFAULT NULL,
  `dotaciPoskytl` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `financniProstredekCleneni` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `financovanoZeZdroje` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `maSmlouvuORozhodnuti` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `refRozhodnutiRok` varchar(50) COLLATE utf8_bin DEFAULT NULL,
  `rokRozhodnuti` int(11) DEFAULT NULL,
  `rozpoctoveObdobi` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `zaznamAktualizaceDatumCas` datetime DEFAULT NULL,
  `zaznamIdentifikator` varchar(50) COLLATE utf8_bin NOT NULL,
  `zaznamPlatnostDatum` datetime DEFAULT NULL,
  `menaKod` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `investiceIndikator` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `navratnostIndikator` varchar(5) COLLATE utf8_bin DEFAULT NULL,
  `title` varchar(100) COLLATE utf8_bin DEFAULT NULL,
  `splatkaKalendar` varchar(150) COLLATE utf8_bin DEFAULT NULL,
  `modified` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `about` (`about`),
  UNIQUE KEY `zaznamIdentifikator` (`zaznamIdentifikator`),
  KEY `castkaPozadovana` (`castkaPozadovana`),
  KEY `castkaRozhodnuta` (`castkaRozhodnuta`),
  KEY `dotaciPoskytl` (`dotaciPoskytl`),
  KEY `financniProstredekCleneni` (`financniProstredekCleneni`),
  KEY `financovanoZeZdroje` (`financovanoZeZdroje`),
  KEY `maSmlouvuORozhodnuti` (`maSmlouvuORozhodnuti`),
  KEY `refRozhodnutiRok` (`refRozhodnutiRok`),
  KEY `rokRozhodnuti` (`rokRozhodnuti`),
  KEY `rozpoctoveObdobi` (`rozpoctoveObdobi`),
  KEY `zaznamAktualizaceDatumCas` (`zaznamAktualizaceDatumCas`),
  KEY `zaznamPlatnostDatum` (`zaznamPlatnostDatum`),
  KEY `menaKod` (`menaKod`),
  KEY `investiceIndikator` (`investiceIndikator`),
  KEY `navratnostIndikator` (`navratnostIndikator`),
  KEY `title` (`title`),
  KEY `splatkaKalendar` (`splatkaKalendar`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
