CREATE TABLE `rozpoctove_obdobi` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `castkaCerpana` decimal(10,2) DEFAULT NULL,
 `castkaSpotrebovana` decimal(10,2) DEFAULT NULL,
 `castkaUvolnena` decimal(10,2) DEFAULT NULL,
 `dotaceTitul` varchar(150) COLLATE utf8_bin DEFAULT NULL,
 `refRozpoctoveObdobi` varchar(50) COLLATE utf8_bin DEFAULT NULL,
 `rozpocetObdobi` int(11) DEFAULT NULL,
 `ucelZnak` varchar(150) COLLATE utf8_bin DEFAULT NULL,
 `zaznamAktualizaceDatumCas` datetime DEFAULT NULL,
 `zaznamIdentifikator` varchar(50) COLLATE utf8_bin NOT NULL,
 `zaznamPlatnostDatum` datetime DEFAULT NULL,
 `menaKod` varchar(5) COLLATE utf8_bin DEFAULT NULL,
 `title` varchar(150) COLLATE utf8_bin DEFAULT NULL,
 `castkaVracena` decimal(10,2) DEFAULT NULL,
 `about` varchar(150) COLLATE utf8_bin NOT NULL,
 `modified` datetime DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`),
 UNIQUE KEY `about` (`about`),
 UNIQUE KEY `zaznamIdentifikator` (`zaznamIdentifikator`),
 KEY `castkaCerpana` (`castkaCerpana`),
 KEY `castkaSpotrebovana` (`castkaSpotrebovana`),
 KEY `castkaUvolnena` (`castkaUvolnena`),
 KEY `dotaceTitul` (`dotaceTitul`),
 KEY `refRozpoctoveObdobi` (`refRozpoctoveObdobi`),
 KEY `rozpocetObdobi` (`rozpocetObdobi`),
 KEY `ucelZnak` (`ucelZnak`),
 KEY `zaznamAktualizaceDatumCas` (`zaznamAktualizaceDatumCas`),
 KEY `zaznamPlatnostDatum` (`zaznamPlatnostDatum`),
 KEY `menaKod` (`menaKod`),
 KEY `title` (`title`),
 KEY `castkaVracena` (`castkaVracena`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COLLATE=utf8_bin
